#!/usr/bin/python

import matplotlib.pyplot as plt
import sys
import math
import os
import numpy as np

#fonction somme f(x)
def fonction(n, x):
        k = 0
        f = 1
        while (k <= n):
                if (x != 0):
                        f = f * (np.sin(x / ((2 * k) + 1)) / (x / ((2 * k) + 1)))
                k = k + 1
        return(f)

def rectangle(n):
        func = 0
        i = 0
        h = float(5000) / float(10000)
        while (i < 10000):
                func = func + fonction(n, i * h)
                i = i + 1
        integrale = h * func
        print("Methode des rectangles")
        print("I" + str(n) + " = " + "%.10f" %integrale)
        print("diff = " + "%.10f" %(integrale - np.pi / 2))

def trapeze(n):
        func = 0
        intgrale = 0
        i = 1
        h = float(5000) / float(10000)
        h2 = h / 2
        while (i < 10000):
                func = func + fonction(n, i * h)
                i = i + 1
        integrale = h2 * ((func * 2) + fonction(n, 0) + fonction(n, 5000))
        print("Methode des trapezes")
        print("I" + str(n) + " = " + "%.10f" %integrale)
        print("diff = " + "%.10f" %(integrale - np.pi / 2))

def simpson(n):
        func1 = 0
        func2 = 0
        integrale = 0
        h = float(5000) / float(10000)
        h6 = h / 6
        i = 1
        while (i < 10000):
                func1 = func1 + fonction(n, i * h)
                i = i + 1
        i = 0
        while (i < 10000):
                func2 = func2 + fonction(n, (i * h) + (h / 2))
                i = i + 1
        integrale = h6 * ((func1 * 2) + (func2 * 4) + fonction(n, 0) + fonction(n, 5000))
        print("Methode de Simpson")
        print("I" + str(n) + " = " + "%.10f" %integrale)
        print("diff = " + "%.10f" %(integrale - np.pi / 2))

try:
        if (len(sys.argv) == 2):
                n = int(sys.argv[1])
                rectangle(n)
                trapeze(n)
                simpson(n)
        else:
                print('You have to write at most 1 argument')
except:
        print('Error...')
        sys.exit(-1)
